# Generated by Django 3.2.6 on 2021-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
