# Generated by Django 3.2.6 on 2021-11-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.PositiveIntegerField()),
                ('existencia', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
    ]
