# Generated by Django 3.2.6 on 2021-11-17 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_factura', models.PositiveIntegerField()),
                ('fecha', models.DateField(max_length=200)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.cliente')),
            ],
            options={
                'db_table': 'Cabecera',
            },
        ),
    ]
