# Generated by Django 3.2.6 on 2021-11-17 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_cabecera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField(blank=True, null=True)),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.cabecera')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.producto')),
            ],
            options={
                'db_table': 'Detalle',
            },
        ),
    ]
