
"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.db import connection
from pathlib import Path
import os
import sys



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+lx3vjgl&ng1s%1@h)lo@t50zo#aae86rw#a7rs28nf$&4v_4l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'mysite',

    'rest_framework',

    'django_filters', #liberia para filtrar query sets mas simples de la bd
    #se usa junto a rest framework

    'crispy_forms', #para poder filtrar desde la interfaz de rest_framework
    
    'allauth',   # <--
    'allauth.account',   # <--
    'allauth.socialaccount',   # <--
    'allauth.socialaccount.providers.google',   # <--
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

def __ObtenerTemplateDirs():
    dirs = [ os.path.join(PROJECT_PATH, 'templates') ]    
    
    contenido_dirs = os.listdir( os.path.join(PROJECT_PATH, 'vistas' ) )

    for item in contenido_dirs:
        tmpDir = os.path.join(PROJECT_PATH, 'vistas', item)
        
        if os.path.isdir(tmpDir):
            dirs.append(tmpDir)

    return dirs

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': __ObtenerTemplateDirs(),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {

    'asdf': { #Pruebas desarrollo (CLOUD)
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'desarrollo',
        'USER': 'postgres',
        'PASSWORD': 'THPvEQqXc4RCpNRy6HVvCBvtB5CEjARo',
        'HOST': 'ec2-52-67-238-5.sa-east-1.compute.amazonaws.com',
        'PORT':'5432'
    },



    'default': { #Produccion
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'backfinalfront',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': '127.0.0.1',
        'PORT':'5432'
    },


}

db_local_name = BASE_DIR / 'db.sqlite3'

db_default_name = connection.settings_dict['NAME']

if(db_default_name == 'desarrollo'):
    print("Corriendo en la BD de la nube (Desarrollo)")
    #SITE_ID = 2 ## 127.0.0.1:8000 en la bd de la nube
else:
    if(db_default_name == 'desarrolloLocal'):
        print("Corriendo en BD Local de produccion")
        #SITE_ID = 2 ## 127.0.0.1:8000 en la bd produccion


SITE_ID = 2
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es-py'

TIME_ZONE = 'America/Asuncion'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
    "django.contrib.auth.backends.ModelBackend", #<- preguntar para que sirve 
)


LOGIN_REDIRECT_URL = '/'
ACCOUNT_ADAPTER = 'mysite.account_adapter.NoNewUsersAccountAdapter'
LOGIN_URL = 'login' #Si el usuario no esta autenticado lo redirige al login siempre

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    # 'DEFAULT_AUTHENTICATION_CLASSES': [
    #     'rest_framework.authentication.SessionAuthentication',
    # ],

    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated'
    # ],

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend'
    ]

}

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

if 'test' in sys.argv or 'test_coverage' in sys.argv: #Covers regular testing and django-coverage
    DATABASES['default']['ENGINE'] = 'django.db.backends.sqlite3'


import mimetypes

mimetypes.add_type("text/javascript", ".js", True)
mimetypes.add_type("text/javascript", ".ts", True)

EMAIL_HOST = 'smtp.googlemail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'is2equipo10@gmail.com'
EMAIL_HOST_PASSWORD = '12345is2equipo10'
EMAIL_USE_TLS = True




MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

MEDIA_URL = '/media/'